import React from "react";
import Footer from "../Shared/Footer/Footer";
import "./Blogs.css";

const Blogs = () => {
  return (
    <div>
      <div className="container">
        <div className="row px-3 my-5 text-center">
          <h1 className="my-5">Popular Blogs</h1>
          <article className="article">
            <h3 className="">Authorization VS Authentication</h3>
            <p>
              Authorization: In authentication process, the identity of users
              are checked for providing the access to the system. While in this
              process, users or persons are validated. While this process is
              done after the authentication process. While it determines What
              permission do user have.
            </p>
            <p>
              Authentication: In authentication process, the identity of users
              are checked for providing the access to the system. In
              authentication process, users or persons are verified. In
              authentication process, users or persons are verified.
              Authentication determines whether the person is user or not.
            </p>
          </article>
          <article className="article">
            <h3 className="">Why are You Using Firebase?</h3>
            <p>
              I'm using firebase for authentication and to host my website.
              Firebase Authentication aims to make building secure
              authentication systems easy, while improving the sign-in and
              onboarding experience for end users. It provides an end-to-end
              identity solution, supporting email and password accounts, phone
              auth, and Google, Twitter, Facebook, and GitHub login, and more.
            </p>
            <h6>Other Options to Implement Authentication</h6>
            <p>
              Auth0: Auth0 is an easy to implement, adaptable authentication and
              authorization platform. Okta: Okta connects any person with any
              application on any device. Amazon Cognito: Amazon Cognito
              Federated Identities is a web service that delivers scoped
              temporary credentials to mobile devices and other untrusted
              environments.
            </p>
          </article>
          <article className="article">
            <h3 className="">
              What are the Other Services Firebase Provides than Authentication?
            </h3>
            <p>
              Firebase provides different kinds of services that help you to
              develop high-quality mobile and web applications. It is compatible
              with Web, iOS, Android, and OS X clients.
            </p>
            <h5>Services Provided by Firebase:</h5>
            <ul className="text-start">
              <li>
                Hosting: Firebase Hosting provides fast and secure hosting for
                your web app, static and dynamic content, and microservices.
              </li>
              <li>
                Cloud Storage: Firebase Cloud Storage is a modern technology
                that allows for storing and managing various media content
                generated by mobile app users.
              </li>
              <li>
                Cloud Messaging: Firebase is a great tool to implement
                notifications, irrespective of the platform because it is fast,
                reliable, and scalable to handle requests.
              </li>
              <li>
                Google Analytics: Google Analytics for Firebase provides free,
                unlimited reporting on up to 500 distinct events.
              </li>
            </ul>
          </article>
        </div>
      </div>
      <Footer></Footer>
    </div>
  );
};

export default Blogs;
